Move to std network types
demikernel/runtime pull request #33
Opened 2022-07-22 17:11 UTC by anandbonde

This is a part of a multi-part series of PRs. This series aims to move from custom types that support network-related data structures to standard library types in Rust. Multiple other PRs will follow targetting similar changes to other libraries (e.g. inetstack, demikernel).

2022-07-22 17:28 UTC, ppenna requested changes
Beyond on the requested changes, I'd add a few suggestions concerning the PR itself:

- Rename the title of the PR to match the following pattern: "[module] Brief Description". We've been following this pattern so far and it helps to search for issues and PRs on our repositories.
- Link on the PR description the concerned issue.

2022-07-22 17:28 UTC, ppenna commented on src/network/types/ip.rs
> +pub use ::std::net::IpAddr;
We don't need this file anymore.

Could you drop it and include `::std::net::IpAddr` wherever it is required?

2022-07-22 18:22 UTC, anandbonde commented on src/network/types/ip.rs
> +pub use ::std::net::IpAddr;
Done

2022-07-22 18:23 UTC, anandbonde commented
> 

Addressed all the comments.

2022-07-25 12:14 UTC, ppenna approved these changes
Looks good now.

When merging, please remember to rebase your branch with latest commits on `dev`.

2022-07-25 16:18 UTC, merged